server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  server:
    # Activer la protection d'auto-préservation
    enable-self-preservation: true
    # Augmenter l'intervalle de nettoyage pour plus de stabilité
    eviction-interval-timer-in-ms: 3000
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    # Augmenter l'intervalle de renouvellement du bail
    lease-renewal-interval-in-seconds: 30
    # Augmenter le délai d'expiration du bail
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO