spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/patients/**
        - id: practitioner-service
          uri: lb://practitioner-service
          predicates:
            - Path=/practitioners/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
    instances:
      patientService:
        baseConfig: default
      practitionerService:
        baseConfig: default
      appointmentService:
        baseConfig: default
      medicalRecordService:
        baseConfig: default